// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings to `simple_cpp`.
class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int simple_add(
    int x,
    int y,
  ) {
    return _simple_add(
      x,
      y,
    );
  }

  late final _simple_add_ptr =
      _lookup<ffi.NativeFunction<_c_simple_add>>('simple_add');
  late final _dart_simple_add _simple_add =
      _simple_add_ptr.asFunction<_dart_simple_add>();
}

typedef _c_simple_add = ffi.Int32 Function(
  ffi.Int32 x,
  ffi.Int32 y,
);

typedef _dart_simple_add = int Function(
  int x,
  int y,
);
