name: dart_ffi_classes

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  ffigen: ^3.0.0
  lints: ^1.0.1

ffigen:
  name: SimpleCPP
  description: Bindings to `simple_cpp`.
  output: 'generated_bindings.dart'
  headers:
    entry-points:
      - 'simple_cpp/simple.h'
  functions:
    include:
      - 'simple_.*'
  macros:
    include:
      - nothing
  enums:
    include:
      - nothing
  unnamed-enums:
    include:
      - nothing
  globals:
    include:
      - nothing
  structs:
    include:
      - simple_.*
    dependency-only: opaque
